apiVersion: v2
name: counter-app
description: A Helm chart for the counter application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cassandra
    version: "10.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    alias: cassandra
  - name: kafka
    version: "26.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kafka
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
