apiVersion: v2
name: counter-app
description: A Helm chart for the counter application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: ""
    repository: "https://charts.jetstack.io"
    alias: cert-manager
  - name: strimzi-kafka-operator
    version: "^0.49.0"
    repository: "https://strimzi.io/charts"
    alias: kafka
  - name: redis
    version: "^23.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
  - name: cass-operator
    version: "0.62.1"
    repository: "https://helm.k8ssandra.io/stable"
    alias: cass-operator
